# Disable some built-in rules
config:
  reference-links-images:
    shortcut_syntax: true
  no-trailing-spaces: false
  no-multiple-blanks: false
  line-length: false
  ul-style: false
  link-fragments:
    ignore_case: false
  no-duplicate-heading:
    siblings_only: true

# Fix any fixable errors
# fix: true

gitignore: true

# Define glob expressions to use (only valid at root)
globs:
  - "**/*.md"

ignores:
  - "example/**"

outputFormatters:
  [[markdownlint-cli2-formatter-default]]
