version: 2

defaults: &defaults
  working_directory: ~/repo
  environment:
    LC_ALL: C.UTF-8

install_hex_rebar: &install_hex_rebar
  run:
    name: Install hex and rebar
    command: |
      mix local.hex --force
      mix local.rebar --force

install_system_deps: &install_system_deps
  run:
    name: Install system dependencies
    command: |
      apk add build-base

jobs:
  build_elixir_1_14_otp_26:
    docker:
      - image: hexpm/elixir:1.14.4-erlang-26.0-alpine-3.18.0
    <<: *defaults
    steps:
      - checkout
      - <<: *install_hex_rebar
      - <<: *install_system_deps
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
            - v1-mix-cache-
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix test --include inclusion --include integration --include firmware_update
      - store_test_results:
          path: test-junit-report.xml
      - run: mix deps.unlock --check-unused
      - run: mix docs
      - run: mix hex.build
      - run: MIX_ENV=test mix credo -a
      - run: mix dialyzer
      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps

  build_elixir_1_14_otp_25:
    docker:
      - image: hexpm/elixir:1.14.3-erlang-25.2.3-alpine-3.18.0
    <<: *defaults
    steps:
      - checkout
      - <<: *install_hex_rebar
      - <<: *install_system_deps
      - run: mix deps.get
      - run: mix compile
      - run: mix test

  build_elixir_1_13_otp_25:
    docker:
      - image: hexpm/elixir:1.13.4-erlang-25.3.2-alpine-3.18.0
    <<: *defaults
    steps:
      - checkout
      - <<: *install_hex_rebar
      - <<: *install_system_deps
      - run: mix deps.get
      - run: mix compile
      - run: mix test

workflows:
  version: 2
  build_test:
    jobs:
      - build_elixir_1_14_otp_26
      - build_elixir_1_14_otp_25
      - build_elixir_1_13_otp_25
